services:
  - type: static
    name: app-frontend
    rootDir: frontend
    buildCommand: "yarn install && yarn build"
    staticPublishPath: build

  - type: web
    name: app-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
